### ISSUE TITLE
Could not find file ...\Bootstrap-edX-master\edx  Demos\ModuleThree\ModuleThree.csproj'. 

### ISSUE THREAD

**Issue by fcumstead** [MicrosoftLearning/Bootstrap-edX#1]
After downloading and extract the master.zip file, when I opened edx Demos.sln I received an error in Visual Studios that ModuleThree.csproj could not be found. I reviewed the branch on GitHub and it was missing from there also.  Is this to be expected? or was there a missed sync of the project files to github?

**Comment by GeekTrainer** [comment]
Looks like the proj file didn't get pushed the first time through. Sorry about that. All should be good now.
